name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update Git submodules
      run: git submodule update --init --recursive

    - name: CMake build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: Check code formatting
      run: ./check-fmt.sh
