name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update Git submodules
      run: git submodule update --init --recursive

    - name: Install clang-tools
      run: sudo apt-get install clang-tools

    - name: CMake build
      run: |
        mkdir build
        cd build
        cmake ..
        scan-build --use-analyzer /usr/bin/clang cmake -DCMAKE_C_COMPILER=clang --build .

    - name: Tests
      run: |
        mkdir tests/build
        cd tests/build
        cmake ..
        cmake --build .
        ./tests

    - name: Check code formatting
      run: bash scripts/check-fmt.sh
